sudo: required
os: linux
services:
  - docker

before_install:
  - docker pull vowpalwabbit/travis-base:travis-ci-test
script:
  - docker run -a STDOUT -v $TRAVIS_BUILD_DIR/VowpalWabbit/vowpal_wabbit:/vw -t vowpalwabbit/travis-base:travis-ci-test /bin/bash -c "cd /vw && ./build-linux.sh"

# after_success:
#   - coveralls --exclude lib --exclude tests --gcov-options '\-lp'
