version: 1.0.{build}
os: Visual Studio 2015 RC
configuration: Debug,Release
platform: x64
shallow_clone: true
clone_folder: C:\vowpal_wabbit
build:
  project: C:\vowpal_wabbit\vowpalwabbit\vw.sln
  parallel: true
  verbosity: detailed
