version: 1.0.{build}
os: Windows Server 2012 R2
image: Visual Studio 2017
configuration:
- Release
platform: x64
shallow_clone: true
clone_folder: C:\vowpal_wabbit
# need to install nuget packages before Visual Studio starts to make ANTLR targets available.
build_script:
- cd c:\vowpal_wabbit
- '"C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MsBuild.exe" "C:\vowpal_wabbit\cs\explore\ds_explore_cs.sln" /m /verbosity:normal "/p:Configuration=Release;Platform=Any CPU"'
- vowpalwabbit\.nuget\nuget install -o vowpalwabbit\packages cs\cs\packages.config
- vowpalwabbit\.nuget\nuget install -o vowpalwabbit\packages cs\azure\packages.config
- vowpalwabbit\.nuget\nuget install -o vowpalwabbit\packages cs\azure_worker\packages.config
- vowpalwabbit\.nuget\nuget install -o vowpalwabbit\packages cs\setup_bundle\packages.config
- vowpalwabbit\.nuget\nuget install -o vowpalwabbit\packages cs\unittest\packages.config
- vowpalwabbit\.nuget\nuget install -o vowpalwabbit\packages python\windows27\packages.config
- vowpalwabbit\.nuget\nuget install -o vowpalwabbit\packages python\windows35\packages.config
- vowpalwabbit\.nuget\nuget install -o vowpalwabbit\packages vowpalwabbit\packages.config
- '"C:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe" "C:\vowpal_wabbit\vowpalwabbit\vw.sln" /m /verbosity:normal /p:Configuration=Release;Platform=x64'
test_script:
- ps: >-
    cd c:\vowpal_wabbit
    bin\Release\ds_explore_cs_test.exe test\explore\test1-input.txt test\explore\test1-expected.txt
    if($env:PLATFORM -eq "x64")

    {
       vstest.console /Platform:x64 /inIsolation vowpalwabbit\x64\Release\cs_unittest.dll /TestCaseFilter:"TestCategory!=NotOnVSO"
    }
on_failure:
- ps: Get-ChildItem C:\Users\appveyor\AppData\Local\CrashDumps\\*.dmp | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
