variables:
  - buildVersionStamp: $(SourceBranchName)_$(Date:yyyyMMdd).$(Rev:.r)

name: $(buildVersionStamp)

pool:
  vmImage: 'ubuntu-16.04'

# Trigger dockerfile to build when updated on master
trigger:
  branches:
    include:
    - master
  paths:
    include:
    - Dockerfile

steps:
  - script: docker build -t $(dockerOrgId)/$(imageName):$(buildVersionStamp) .
  - script: docker login -u "$(dockerCredId)" -p "$(pswd)" https://index.docker.io/v1/
  - script: docker push $(dockerOrgId)/$(imageName):$(buildVersionStamp)

# To use this pushed docker image on the CI, the image must be tagged as latest.