trigger:
  branches:
    include:
    - master
  paths:
    include:
    - .pipelines/build-linux-valgrind.yml
    - .scripts/linux/**
    - cluster/**
    - cmake/**
    - cs/**
    - explore/**
    - ext_libs/**
    - library/**
    - test/**
    - vowpalwabbit/**
    - CMakeLists.txt
    - version.txt

pr:
  branches:
    include:
    - master
  paths:
    include:
    - .pipelines/build-linux-valgrind.yml
    - .scripts/linux/**
    - cluster/**
    - cmake/**
    - cs/**
    - explore/**
    - ext_libs/**
    - library/**
    - test/**
    - vowpalwabbit/**
    - CMakeLists.txt
    - version.txt

pool:
  vmImage: 'ubuntu-16.04'

container:
  image: vowpalwabbit/ubuntu1604-build:latest
  endpoint: DockerHub

steps:
- bash: |
    sudo apt update -y
    sudo apt install -y valgrind
  displayName: Install Valgrind
- bash: ./.scripts/linux/build-minimal.sh Release
  displayName: Build C++ VW binary
- bash: ./.scripts/linux/test-valgrind.sh
  displayName: Run test suite with Valgrind
- bash: ./.scripts/linux/unit-tests-valgrind.sh
  displayName: Run unit tests with Valgrind
