name: Build Documentation

on: [push]

jobs:
  CXX:
    container:
      image: vowpalwabbit/ubuntu1604-build:0.4.0
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Doxygen
        run: |
          apt install -y doxygen graphviz
      - name: Configure
        run: |
          mkdir build
          cd build
          cmake .. -DBUILD_DOCS=On
      - name: Build docs
        run: |
          cd build
          make doc
      - name: Upload built docs
        uses: actions/upload-artifact@v1
        with:
          name: cxx_docs
          path: doc/html/
  Python:
    container:
      image: vowpalwabbit/ubuntu1604-build:0.4.0
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Python package
        run: |
          /usr/local/miniconda/bin/activate test-python36
          python setup.py install --user
          /usr/local/miniconda/bin/deactivate
      - name: Build docs
        run: |
          /usr/local/miniconda/bin/activate test-python36
          cd python/docs
          pip install sphinx numpy sklearn scipy numpydoc
          make html
          /usr/local/miniconda/bin/deactivate
      - name: Upload built docs
        uses: actions/upload-artifact@v1
        with:
          name: python_docs
          path: python/docs/build/
  Upload:
    name: Upload Docs
    needs: [CXX, Python]
    runs-on: ubuntu-latest
    steps:
      - name: Download CXX Docs
        uses: actions/download-artifact@v1
        with:
          name: cxx_docs
      - name: Download Python Docs
        uses: actions/download-artifact@v1
        with:
          name: python_docs
      - name: Print contents of directory
        shell: bash
        run: |
          pwd
          ls
      - uses: actions/checkout@v1
        with:
          repository: jackgerrits/docs
          ref: master
          path: ${{github.workspace}}/docs
      - name: Print contents of directory
        shell: bash
        run: |
          pwd
          ls
      - name: Copy CXX Docs
        shell: bash
        run: |
          rm -rf docs/vowpal_wabbit/cpp/latest/
          mkdir -p docs/vowpal_wabbit/cpp/latest/
          cp -r cxx_docs docs/vowpal_wabbit/cpp/latest/
      - name: Copy Python Docs
        shell: bash
        run: |
          rm -rf docs/vowpal_wabbit/python/latest/
          mkdir -p docs/vowpal_wabbit/python/latest/
          cp -r python_docs/html/ docs/vowpal_wabbit/python/latest/
      - name: Commit and push
        shell: bash
        working-directory: ${{github.workspace}}/docs
        run: |
          git checkout master
          git add --all
          git commit -m "Update documentation for commit: ${{ github.sha }}""
          git push origin master
