name: Build and test VWSlim
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  Coverage:
    container:
      image: vowpalwabbit/ubuntu1604-build:latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install GTest
        shell: bash
        run: ./.scripts/linux/install-gtest.sh
      - name: Build VWSlim
        shell: bash
        run: ./.scripts/linux/build-slim.sh
      - name: Test VWSlim
        shell: bash
        run: ./.scripts/linux/build-slim.sh