name: Windows cmake build
on: [push]

jobs:
  job:
    name: windows-cmake-build
    runs-on: windows-latest
    env:
      CMAKE_BUILD_DIR: ${{ github.workspace }}/vw/build
      SOURCE_DIR: ${{ github.workspace }}/vw
      VCPKG_ROOT: ${{ github.workspace }}/vcpkg

    steps:
      - uses: actions/checkout@v2
        with:
          path: 'vw'
          submodules: true
      - uses: actions/checkout@v2
        with:
          path: 'vcpkg'
          repository: 'microsoft/vcpkg'
          submodules: true
      - name: Restore vcpkg and its artifacts.
        uses: actions/cache@v2
        with:
          path: |
            ${{ env.VCPKG_ROOT }}/installed/
            ${{ env.VCPKG_ROOT }}
            !${{ env.VCPKG_ROOT }}/buildtrees
            !${{ env.VCPKG_ROOT }}/packages
            !${{ env.VCPKG_ROOT }}/downloads
          key: |
              x64-windows-invalidate
      - name: Show content of workspace after cache has been restored
        run: find $RUNNER_WORKSPACE
        shell: bash
      - uses: ilammy/msvc-dev-cmd@v1
      - run: ${{ env.VCPKG_ROOT }}/bootstrap-vcpkg.bat
      - run: ${{ env.VCPKG_ROOT }}/vcpkg.exe --triplet x64-windows install zlib boost-system boost-program-options boost-test boost-align boost-foreach boost-math flatbuffers
      - name: Install dependencies and generate project files
        run: |
          cmake -S "${{ env.SOURCE_DIR }}" -B "${{ env.CMAKE_BUILD_DIR }}" -GNinja -DCMAKE_TOOLCHAIN_FILE="${{ env.VCPKG_ROOT }}/scripts/buildsystems/vcpkg.cmake"
      - name: Build
        run: |
          cmake --build "${{ env.CMAKE_BUILD_DIR }}"
