name: Run benchmarks for refs
on:
  workflow_dispatch:
    inputs:
      base_ref:
        description: 'Base git ref to benchmark'
        required: true
        default: '8.9.0'
      compare_ref:
        description: 'Git ref to benchmark against base'
        required: true
        default: 'master'

jobs:
  Benchmarking:
    container:
      image: vowpalwabbit/ubuntu1604-build:latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          ref: ${{ github.event.inputs.base_ref }}
      - name: Install google benchmarks
        shell: bash
        run: ./.scripts/linux/install-benchmark.sh
      - name: Build ${{ github.event.inputs.base_ref }}
        shell: bash
        run: ./.scripts/linux/build-with-benchmarks.sh
      - name: Benchmark ${{ github.event.inputs.base_ref }}
        shell: bash
        run: ./.scripts/linux/run-benchmarks.sh base-benchmarks.json
      - name: Upload ${{ github.event.inputs.base_ref }} benchmark results
        uses: actions/upload-artifact@v2
        with:
          name: base-benchmarks
          path: base-benchmarks.json
      - name: Upload benchmark compare
        uses: actions/upload-artifact@v2
        with:
          name: benchmark-compare
          path: benchmark/tools/
      - name: Install benchmark compare requirements
        shell: bash
        run: /usr/local/miniconda/envs/test-python36/bin/pip install -r benchmark/tools/requirements.txt
      - run: rm -rf benchmark build vowpalwabbit/parser/flatbuffer/generated/ # generated or downloaded files
      - uses: actions/checkout@v1
        with:
          ref: ${{ github.event.inputs.compare_ref }}
      - name: Download ${{ github.event.inputs.base_ref }} benchmark results
        uses: actions/download-artifact@v2
        with:
          name: base-benchmarks
      - name: Download benchmark compare
        uses: actions/download-artifact@v2
        with:
          name: benchmark-compare
      - name: Build ${{ github.event.inputs.compare_ref }}
        shell: bash
        run: ./.scripts/linux/build-with-benchmarks.sh
      - name: Benchmark ${{ github.event.inputs.compare_ref }}
        shell: bash
        run: ./.scripts/linux/run-benchmarks.sh compare-benchmarks.json
      - name: Compare benchmarks
        shell: bash
        run: ./.scripts/linux/compare-benchmarks.sh base-benchmarks.json compare-benchmarks.json
